In [16]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


In [5]:
device = 'cuda' if torch.cuda.is_available() else "cpu"

In [6]:
# Initializing Tensor
my_tensor = torch.tensor([[1,2,3],[4,5,6],[7,8,9]],dtype=torch.float32,
                         device=device, requires_grad=True)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], requires_grad=True)


In [10]:
my_tensor.device

device(type='cpu')

In [11]:
my_tensor.requires_grad

True

In [15]:
torch.__version__

'2.5.1+cu121'

## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using torch.Tensor()

In [19]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [20]:
scalar.ndim

0

In [22]:
# Get tensor back as Python int
scalar.item()

7

In [24]:
# Vector
vector = torch.tensor([7, 7])
vector.ndim

1

In [25]:
vector.shape

torch.Size([2])

In [28]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [29]:
MATRIX.ndim

2

In [30]:
MATRIX[0]

tensor([7, 8])

In [31]:
MATRIX[1]

tensor([ 9, 10])

In [32]:
MATRIX.shape

torch.Size([2, 2])

In [33]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                       [3, 6, 9],
                       [2, 4, 5]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [34]:
TENSOR.ndim

3

In [35]:
TENSOR.shape

torch.Size([1, 3, 3])

In [37]:
a = torch.tensor([[[1, 2],
                   [2, 3],
                   [3, 4,]]])


In [39]:
a.ndim

3

In [41]:
a.size()

torch.Size([1, 3, 2])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that tthey start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [44]:
# Create a random tensor of shape or size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9048, 0.7732, 0.1307, 0.1567],
        [0.8702, 0.1259, 0.0107, 0.0138],
        [0.6471, 0.5896, 0.5545, 0.6219]])

In [45]:
random_tensor.ndim

2

In [47]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [48]:
torch.rand(size=(3, 3))

tensor([[0.1946, 0.4232, 0.6417],
        [0.8878, 0.4828, 0.9655],
        [0.8406, 0.2991, 0.7346]])

## Zeros and ones

In [51]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [54]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [55]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like


In [61]:
# Use torch.range()
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [68]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [66]:
float_32_tensor.dtype

torch.float32

In [ ]:
from google.colab import drive
drive.mount('/content/drive')